url: "https://www.victorbilgin.com"
baseurl: ""
title: "Victor Bilgin" 
description: "The personal site of Victor Bilgin"
author: "Victor Bilgin"

email: hello@victorbilgin.com

include:
  - _pages
  - _projects
  
collections:
  book-reviews:
    output: true
  movie-reviews:
    output: true
  poems:
    output: true

markdown: kramdown

sass:
  style: compressed

highlighter: rouge