url: "https://www.victorbilgin.com"
baseurl: ""
title: "Victor Bilgin" 
description: "My personal site for blog posts, book reviews, and other projects."
author: "Victor Bilgin"

plugins:
  - jekyll-feed

email: hello@victorbilgin.com

include:
  - _pages
  - _projects
  
collections:
  book-reviews:
    output: true
  movie-reviews:
    output: true
  poems:
    output: true

markdown: kramdown

sass:
  style: compressed

highlighter: rouge