# This is a basic workflow to help you get started with Actions

name: Build and deploy Jekyll site

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest # can change this to ubuntu-latest if you prefer
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: 'placeholder'
          
      - name: Add known_hosts
        run: ssh-keyscan -H victorbilgin.com >> ~/.ssh/known_hosts
        
      - name: Set up ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.1

      - name: Install dependencies & build site
        uses: limjh16/jekyll-action-ts@v2
        with:
          enable_cache: true
          
      - name: Deploy via rsync
        run: rsync -avz --delete ./_site/ ${{ secrets.REMOTE_USER }}@victorbilgin.com:${{ secrets.REMOTE_DIR }}
